# Generated by Django 3.0.5 on 2020-05-16 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRadnje',
            fields=[
                ('id_radnje', models.AutoField(primary_key=True, serialize=False)),
                ('datum', models.DateField(blank=True, null=True)),
                ('opis', models.CharField(blank=True, max_length=500, null=True)),
                ('napomena', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'admin_radnje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dobavljac',
            fields=[
                ('oznaka_dobavljaca', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('puni_naziv', models.CharField(blank=True, max_length=45, null=True)),
                ('adresa', models.CharField(blank=True, max_length=45, null=True)),
                ('kontakt', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'dobavljac',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Komponenete',
            fields=[
                ('id_komponenete', models.AutoField(primary_key=True, serialize=False)),
                ('vrsta', models.CharField(blank=True, max_length=45, null=True)),
                ('proizvodac', models.CharField(blank=True, max_length=45, null=True)),
                ('model', models.CharField(blank=True, max_length=45, null=True)),
                ('opis', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'komponenete',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Konfiguracija',
            fields=[
                ('id_konfiguracija', models.AutoField(primary_key=True, serialize=False)),
                ('stanje', models.CharField(blank=True, max_length=31, null=True)),
                ('napomena', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'konfiguracija',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id_korisnik', models.AutoField(primary_key=True, serialize=False)),
                ('ime', models.CharField(blank=True, max_length=45, null=True)),
                ('prezime', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('telefon', models.CharField(blank=True, max_length=45, null=True)),
                ('radno_mjesto', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'korisnik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nabava',
            fields=[
                ('id_nabave', models.AutoField(primary_key=True, serialize=False)),
                ('datum', models.DateField(blank=True, null=True)),
                ('napomena', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'nabava',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Odjel',
            fields=[
                ('oznaka_odjela', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'odjel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizacijskaJedinica',
            fields=[
                ('oznaka_org_jed', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('naziv', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'organizacijska_jedinica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Programi',
            fields=[
                ('id_programa', models.AutoField(primary_key=True, serialize=False)),
                ('naziv_programa', models.CharField(max_length=45)),
                ('proizvodac', models.CharField(blank=True, max_length=45, null=True)),
                ('licenca', models.CharField(blank=True, max_length=45, null=True)),
                ('napomena', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'programi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prostorija',
            fields=[
                ('oznaka_prostorije', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('kat', models.IntegerField(blank=True, null=True)),
                ('namjena', models.CharField(blank=True, max_length=45, null=True)),
                ('napomena', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'prostorija',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uredaj',
            fields=[
                ('id_uredaj', models.AutoField(primary_key=True, serialize=False)),
                ('vrsta', models.CharField(blank=True, max_length=47, null=True)),
                ('hostname_ip', models.CharField(blank=True, db_column='hostname_IP', max_length=45, null=True)),
                ('napomena', models.CharField(blank=True, max_length=500, null=True)),
                ('istek_garancije', models.DateField(blank=True, null=True)),
                ('proizvodac', models.CharField(blank=True, max_length=45, null=True)),
                ('model', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'uredaj',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zahtjev',
            fields=[
                ('id_zahtjev', models.AutoField(primary_key=True, serialize=False)),
                ('datum', models.DateField(blank=True, null=True)),
                ('nacin_podnosenja', models.CharField(max_length=40)),
                ('opis', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=29)),
                ('napomena', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'zahtjev',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zgrada',
            fields=[
                ('oznaka_zgrade', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=45)),
                ('adresa', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'zgrada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminOvlasti',
            fields=[
                ('id_uredaj', models.OneToOneField(db_column='id_uredaj', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='galeb.Uredaj')),
                ('lokalni_admin', models.CharField(max_length=45)),
                ('datum_kreiranja', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admin_ovlasti',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InstaliraniProgrami',
            fields=[
                ('id_programa', models.OneToOneField(db_column='id_programa', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='galeb.Programi')),
            ],
            options={
                'db_table': 'instalirani_programi',
                'managed': False,
            },
        ),
    ]
