# Generated by Django 3.0.5 on 2020-06-04 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminovlasti',
            options={'managed': False, 'verbose_name_plural': 'Adminovlasti'},
        ),
        migrations.AlterModelOptions(
            name='adminradnje',
            options={'managed': False, 'verbose_name_plural': 'Aminradnje'},
        ),
        migrations.AlterModelOptions(
            name='dobavljac',
            options={'managed': False, 'verbose_name_plural': 'Dobavljaci'},
        ),
        migrations.AlterModelOptions(
            name='instaliraniprogrami',
            options={'managed': False, 'verbose_name_plural': 'Instaliraniprogrami'},
        ),
        migrations.AlterModelOptions(
            name='komponenete',
            options={'managed': False, 'verbose_name_plural': 'Komponenete'},
        ),
        migrations.AlterModelOptions(
            name='konfiguracija',
            options={'managed': False, 'verbose_name_plural': 'Konfiguracije'},
        ),
        migrations.AlterModelOptions(
            name='korisnik',
            options={'managed': False, 'verbose_name_plural': 'Korisnici'},
        ),
        migrations.AlterModelOptions(
            name='nabava',
            options={'managed': False, 'verbose_name_plural': 'Nabave'},
        ),
        migrations.AlterModelOptions(
            name='odjel',
            options={'managed': False, 'verbose_name_plural': 'Odjeli'},
        ),
        migrations.AlterModelOptions(
            name='organizacijskajedinica',
            options={'managed': False, 'verbose_name_plural': 'Organizacijskejedinice'},
        ),
        migrations.AlterModelOptions(
            name='programi',
            options={'managed': False, 'verbose_name_plural': 'Programi'},
        ),
        migrations.AlterModelOptions(
            name='prostorija',
            options={'managed': False, 'verbose_name_plural': 'Prostorije'},
        ),
        migrations.AlterModelOptions(
            name='uredaj',
            options={'managed': False, 'verbose_name_plural': 'Uredaji'},
        ),
        migrations.AlterModelOptions(
            name='zahtjev',
            options={'managed': False, 'ordering': ['-datum'], 'verbose_name_plural': 'Zathjevi'},
        ),
        migrations.AlterModelOptions(
            name='zgrada',
            options={'managed': False, 'verbose_name_plural': 'Zgrade'},
        ),
        migrations.AlterModelTable(
            name='programi',
            table='Programi',
        ),
    ]
