# Generated by Django 3.0.5 on 2020-06-04 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeb', '0003_auto_20200604_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='konfiguracija',
            options={'managed': True, 'verbose_name_plural': 'Konfiguracije'},
        ),
    ]
